Recaptcha
Representable/representable pull request #479
Opened 2020-11-25 09:53 UTC by jessiejofielding

**Changes:**
- implements recaptcha v2 checkbox on the entry page

**To test:**
- runserver
- check out the entry page, ensure that you can't submit without filling in the captcha
- on dev the captcha will have a red message informing you that this is just a test captcha - this is expected behaviour

**Note:**
- perhaps we should wait until entry page changes have been made, and then move my frontend code to the appropriate place there - it should be two lines of HTML and one js function and one js import, see the code changes here to find them

2020-11-25 20:27 UTC, arorasomya requested changes

2020-11-25 20:55 UTC, jessiejofielding commented on representable/settings/dev.py
> +RECAPTCHA_PRIVATE = "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
I don't think so - the testing keys are the same for every recaptcha user - these are not our keys, and it's a pain to not be able to switch in dev between whether or not we need them to be our keys or the testing keys without changing env variables. We could change our public key in prod to be a variable but it is a public key so it's not important to keep private and it's just a little more bother for it to be in env.

2020-11-25 20:57 UTC, jessiejofielding commented on representable/settings/dev.py
> +RECAPTCHA_PRIVATE = "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
which is to say that every testing recaptcha that is used in development everywhere uses the same keys available from google's recaptcha faq for testing, it's not site or account specific

2020-11-26 01:57 UTC, arorasomya commented on representable/settings/dev.py
> +RECAPTCHA_PRIVATE = "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
Gotcha! Im having a hard time testing locally because of the state page issue, but I looked over the code and it looks good! Sorry it took so long.

2020-11-26 01:58 UTC, arorasomya approved these changes
LGTM!

2020-12-01 14:23 UTC, merged